name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Updated to v4
    
    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to latest
      with:
        python-version: '3.10'  # Newer Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.24.3
        pip install -r requirements.txt
    
    - name: Run training
      run: |
        python src/train.py
        head -n 5 data/iris.csv  # Show first 5 rows of data
        ls -l models/
    
    - name: Test model
      run: python src/test_model.py
    
    - name: Upload model artifact
      uses: actions/upload-artifact@v4  # Critical fix: updated to v4
      with:
        name: iris-model
        path: models/iris_classifier.joblib
        if-no-files-found: error